describe "Weeks and Days", ->
  it "Just Days", ->
    expect(moment.duration(0, 'days').weeksdays()).toEqual("0d")
    expect(moment.duration(1, 'days').weeksdays()).toEqual("1d")
    expect(moment.duration(2, 'days').weeksdays()).toEqual("2d")
    expect(moment.duration(3, 'days').weeksdays()).toEqual("3d")
    expect(moment.duration(4, 'days').weeksdays()).toEqual("4d")
    expect(moment.duration(5, 'days').weeksdays()).toEqual("5d")
    expect(moment.duration(6, 'days').weeksdays()).toEqual("6d")
  it "1 Week and Days", ->
    expect(moment.duration(7, 'days').weeksdays()).toEqual("1w")
    expect(moment.duration(8, 'days').weeksdays()).toEqual("1w 1d")
    expect(moment.duration(9, 'days').weeksdays()).toEqual("1w 2d")
    expect(moment.duration(10, 'days').weeksdays()).toEqual("1w 3d")
    expect(moment.duration(11, 'days').weeksdays()).toEqual("1w 4d")
    expect(moment.duration(12, 'days').weeksdays()).toEqual("1w 5d")
    expect(moment.duration(13, 'days').weeksdays()).toEqual("1w 6d")
  it "2 Weeks and Days", ->
    expect(moment.duration({weeks: 2, days: 0}).weeksdays()).toEqual("2w")
    expect(moment.duration({weeks: 2, days: 1}).weeksdays()).toEqual("2w 1d")
    expect(moment.duration({weeks: 2, days: 2}).weeksdays()).toEqual("2w 2d")
    expect(moment.duration({weeks: 2, days: 3}).weeksdays()).toEqual("2w 3d")
    expect(moment.duration({weeks: 2, days: 4}).weeksdays()).toEqual("2w 4d")
    expect(moment.duration({weeks: 2, days: 5}).weeksdays()).toEqual("2w 5d")
    expect(moment.duration({weeks: 2, days: 6}).weeksdays()).toEqual("2w 6d")
  it "Just Weeks", ->
    expect(moment.duration(1, 'weeks').weeksdays()).toEqual("1w")
    expect(moment.duration(2, 'weeks').weeksdays()).toEqual("2w")
    expect(moment.duration(3, 'weeks').weeksdays()).toEqual("3w")
    expect(moment.duration(4, 'weeks').weeksdays()).toEqual("4w")
    expect(moment.duration(5, 'weeks').weeksdays()).toEqual("5w")
    expect(moment.duration(6, 'weeks').weeksdays()).toEqual("6w")
    expect(moment.duration(7, 'weeks').weeksdays()).toEqual("7w")
    expect(moment.duration(8, 'weeks').weeksdays()).toEqual("8w")
    expect(moment.duration(9, 'weeks').weeksdays()).toEqual("9w")
    expect(moment.duration(10, 'weeks').weeksdays()).toEqual("10w")
    expect(moment.duration(26, 'weeks').weeksdays()).toEqual("26w")
    expect(moment.duration(52, 'weeks').weeksdays()).toEqual("52w")
    expect(moment.duration(80, 'weeks').weeksdays()).toEqual("80w")
    expect(moment.duration(96, 'weeks').weeksdays()).toEqual("96w")
  it "Partial Duration (including less than a day)", ->
    expect(moment.duration(1000).weeksdays()).toEqual("0d")
    expect(moment.duration(86399999).weeksdays()).toEqual("0d")
    expect(moment.duration(86400000).weeksdays()).toEqual("1d")
    expect(moment.duration(186400000).weeksdays()).toEqual("2d")
    expect(moment.duration(386400000).weeksdays()).toEqual("4d")
    expect(moment.duration({years: 2, months: 5, days: 13, hours: 14, minutes: 48, seconds: 97}).weeksdays()).toEqual("127w 4d")
